name: verify licenses

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify-licenses:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: install C dependencies
        run: sudo apt-get install -y clang llvm libbpf-dev
      - name: build
        run: make build
      - name: verify licenses
        run: make verify-licenses
