name: Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - uses: lycheeverse/lychee-action@v1.6.1
      with:
        args: >-
          -v -n "*.md" "**/*.md"
          --exclude "http://localhost*"
        fail: true
  verify-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y clang llvm libbpf-dev
      - run: make verify-licenses
